apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplebackend-deployment
  labels:
    app: samplebackend  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samplebackend
  template:
    metadata:
      labels:
        app: samplebackend
    spec:
      containers:
        - name: samplebackend
          image: samplebackend
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: samplebackend
spec:
  selector:
    app: samplebackend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      